export const errorsMessages: Record<number, string> = {
  10: 'No existe una campaña con el id enviado.',
  11: 'Un parámetro es obligatorio.',
  12: 'El api key usado no es válido.',
  13: 'El api key usado fue desactivado.',
  14: 'Cuenta está inactiva o suspendida.',
  15: 'El módulo que se quiere usar no ha sido configurado.',
  16: 'El IP utilizado no está autorizado.',
  17: 'El typo del request es inválido.',
  20: 'El participante que se quiere acceder no existe en la campaña.',
  21: 'Los datos enviados para registrar el usuario no son válidos.',
  22: 'Los datos enviados para actualizar el usuario no son válidos.',
  23: 'El participante que se quiere acceder fue baneado.',
  24: 'El participante que se quiere activar no está pendiente de ser activado.',
  25: 'El número del participante a verificar ya ha sido enviado y tendrá que esperar antes de enviar uno nuevo.',
  26: 'Los datos enviados para verificar este participante ya han sido usados.',
  30: "La acción del evento que se quiere registrar no ha sido configurada en el módulo 'external'.",
  31: 'Los datos para crear el evento no son válidos.',
  40: 'Error desconocido al ejecutar la actividad del módulo.',
  41: 'La actividad es inválida cuando se ejecutó la actividad.',
  42: 'El participante sobrepaso el limite de actividades del tipo que fue ejecutada.',
  43: 'No hay suficientes puntos para ejecutar la actividad.',
  44: 'El participante que ejecuta la actividad no es válido.',
  45: 'La actividad ya había sido ejecutada.',
  46: 'La actividad está pendiente de moderación.',
  47: 'La actividad fue rechazada.',
  50: 'El cupón con el código usado no existe.',
  51: 'El cupón ya había sido redimido.',
  60: 'La factura que se quiere acceder no fue encontrada.',
  61: 'La compra no es válida.',
  62: 'La devolución de la factura no es válida.',
  63: 'La factura ya existe.',
  70: 'Se ha excedido el límite de peticiones fallidas.',
  71: 'No existen códigos para redimir.',
  72: 'El código no ha sido encontrado.',
  80: 'La pregunta ya fue respondida.',
  90: 'La actividad que se quiere votar no fue encontrada o no existe.',
  91: 'Ya se ha votado por la actividad enviada.',
  100: 'No se encontró el Post.',
  110: 'La actividad que se quiere comentar no fue encontrada o no existe.',
  120: 'El formulario no fue encontrado.',
  121: 'Error al subir los datos del formulario.',
  140: 'El registro del participante está incompleto.',
  141: 'Las credenciales utilizadas son incorrectas.',
  142: 'Se ha alcanzado el límite de intentos para iniciar sesión.',
  143: 'No se ha obtenido una respuesta positiva del Captcha.',
  144: 'El participante no ha sido encontrado.',
  210: 'El particitante ya pertenece a un equipo.',
  214: 'No está permitido crear un equipo.'
}
